# Generated by Django 6.1 on 2026-09-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relocationtask",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relocation_tasks",
                to="fleet.car",
            ),
        ),
    ]
