# Generated by Django 6.1 on 2026-09-11 11:26

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("fleet", "0001_initial"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggregate_type", models.CharField(max_length=200)),
                ("aggregate_id", models.IntegerField()),
                ("event_type", models.CharField(max_length=200)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "global"),
                            ("CITY", "city"),
                            ("STATION", "station"),
                            ("VEHICLE_TYPE", "vehicle_type"),
                            ("VEHICLE", "vehicle"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("SEASONAL", "seasonal"),
                            ("WEEKEND", "weekend"),
                            ("HOLIDAY", "holiday"),
                            ("DEMAND_SURGE", "demand_surge"),
                            ("EARLY_BIRD", "early_bird"),
                            ("LONG_TERM", "long_term"),
                        ],
                        max_length=20,
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                (
                    "valid_period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("multiplier", models.PositiveIntegerField(default=1)),
                ("flat_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("free_km_per_day", models.PositiveIntegerField(default=0)),
                (
                    "price_per_extra_km",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("CONFIRMED", "confirmed"),
                            ("ACTIVE", "active"),
                            ("COMPLETED", "completed"),
                            ("CANCELLED", "cancelled"),
                            ("EXPIRED", "expired"),
                            ("PAYMENT_PENDING", "payment_pending"),
                            ("PAYMENT_FAILED", "payment_failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "idempotency_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("hold_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleet.car"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "dropoff_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropoff_bookings",
                        to="geo.station",
                    ),
                ),
                (
                    "pickup_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_bookings",
                        to="geo.station",
                    ),
                ),
                (
                    "pricing_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="booking.pricingrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_ref",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "deposit"),
                            ("BALANCE", "balance"),
                            ("DEPOSIT_HOLD", "deposit_hold"),
                            ("PENALTY", "penalty"),
                            ("REFUND", "refund"),
                            ("EXTRA_LARGE", "extra_large"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("PROCESSING", "processing"),
                            ("COMPLETED", "completed"),
                            ("FAILED", "failed"),
                            ("CANCELLED", "cancelled"),
                            ("REFUNDED", "refunded"),
                            ("PARTIALLY_REFUNDED", "partially_refunded"),
                            ("EXPIRED", "expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="booking.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField(null=True)),
                (
                    "start_odometer",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("end_odometer", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "extra_km_charged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="booking.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Damage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "damage_type",
                    models.CharField(
                        choices=[
                            ("SCRATCH", "scratch"),
                            ("DENT", "dent"),
                            ("CRACK", "crack"),
                            ("BROKEN", "broken"),
                            ("STAINED", "stained"),
                            ("MISSING_PART", "missing_part"),
                            ("MECHANICAL", "mechanical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "minor"),
                            ("MODERATE", "moderate"),
                            ("SEVERE", "severe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=20)),
                ("description", models.TextField()),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("reported_at", models.DateField()),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rental",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.rental"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed"])),
                expressions=[("car", "="), ("period", "&&")],
                name="exclude_overlapping_bookings",
            ),
        ),
    ]
