# Generated by Django 6.1 on 2026-08-27 10:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("seats", models.IntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("MANUAL", "manual"),
                            ("AUTOMATIC", "automatic"),
                            ("SEMI_AUTOMATIC", "semi_automatic"),
                            ("CTV", "ctv"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("PETROL", "petrol"),
                            ("DIESEL", "diesel"),
                            ("ELECTRIC", "electric"),
                            ("HYBRID", "hybrid"),
                            ("GAS", "gas"),
                        ],
                        default="PETROL",
                        max_length=20,
                    ),
                ),
                (
                    "daily_base_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MANUAL", "manual"),
                            ("AUTOMATIC", "automatic"),
                            ("SEMI_AUTOMATIC", "semi_automatic"),
                            ("CTV", "ctv"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("odometer_km", models.IntegerField()),
                ("fuel_level", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo.station"
                    ),
                ),
                (
                    "carModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleet.carmodel"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["station"], name="car_station_fk"),
                    models.Index(fields=["status"], name="fleet_car_status_d0b34f_idx"),
                ],
            },
        ),
    ]
