# Generated by Django 6.1 on 2026-08-27 10:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("timezone", models.CharField(max_length=30)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("capacity", models.IntegerField()),
                (
                    "geofence",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                ("target_count", models.IntegerField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo.city"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["location"], name="location")],
            },
        ),
    ]
